// <auto-generated />
using System;
using HeuristicLogix.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeuristicLogix.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260202200042_AddMultiDimensionalStockTracking")]
    partial class AddMultiDimensionalStockTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeuristicLogix.Shared.Models.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("BrandId");

                    b.HasIndex("BrandName");

                    b.ToTable("Brands", "Inventory");
                });

            modelBuilder.Entity("HeuristicLogix.Shared.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryName")
                        .HasDatabaseName("IX_Categories_CategoryName");

                    b.ToTable("Categories", "Inventory");
                });

            modelBuilder.Entity("HeuristicLogix.Shared.Models.Conduce", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("AIPredictedServiceTime")
                        .HasColumnType("float");

                    b.Property<double?>("ActualServiceTime")
                        .HasColumnType("float");

                    b.Property<Guid?>("AssignedTruckId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DeliveryDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("DominantMaterialType")
                        .HasColumnType("int");

                    b.Property<string>("ExpertDecisionNote")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("RawAddress")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("RouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("TotalWeightKg")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("Conduces", "Logistics");
                });

            modelBuilder.Entity("HeuristicLogix.Shared.Models.ConduceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConduceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsAutoClassified")
                        .HasColumnType("bit");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaterialType")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProductTaxonomyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConduceId");

                    b.HasIndex("ProductTaxonomyId");

                    b.ToTable("ConduceItem");
                });

            modelBuilder.Entity("HeuristicLogix.Shared.Models.DeliveryRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("EstimatedDistanceKm")
                        .HasColumnType("float");

                    b.Property<double>("EstimatedTotalTimeMinutes")
                        .HasColumnType("float");

                    b.Property<double>("HeuristicEfficiencyScore")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedByExpertId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StopSequence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stops")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalWeightKg")
                        .HasColumnType("float");

                    b.Property<Guid>("TruckId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("WasManuallyOverridden")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledDate");

                    b.HasIndex("Status");

                    b.HasIndex("TruckId");

                    b.ToTable("DeliveryRoutes", "Logistics");
                });

            modelBuilder.Entity("HeuristicLogix.Shared.Models.ExpertHeuristicFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("AIConfidenceScore")
                        .HasColumnType("float");

                    b.Property<Guid?>("AISuggestedTruckId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConduceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("DecisionTimeSeconds")
                        .HasColumnType("float");

                    b.Property<Guid>("ExpertAssignedTruckId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExpertDisplayName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExpertId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExpertNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("MaterialsSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewDropZone")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OriginalDropZone")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PrimaryReasonTag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SecondaryReasonTags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("TrainedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("UsedForTraining")
                        .HasColumnType("bit");

                    b.Property<bool>("WasDragDropAssignment")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ConduceId");

                    b.HasIndex("PrimaryReasonTag");

                    b.HasIndex("RecordedAt");

                    b.ToTable("ExpertHeuristicFeedbacks", "Logistics");
                });

            modelBuilder.Entity("HeuristicLogix.Shared.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int>("BaseUnitOfMeasureId")
                        .HasColumnType("int");

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("CostPricePerBaseUnit")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CurrentStockQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DefaultSalesUnitOfMeasureId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("LocationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MinimumRequiredStockQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ReservedStockQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SellingPricePerBaseUnit")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("StagingStockQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StockKeepingUnitCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TaxConfigurationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ItemId");

                    b.HasIndex("BaseUnitOfMeasureId");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DefaultSalesUnitOfMeasureId");

                    b.HasIndex("StockKeepingUnitCode")
                        .IsUnique();

                    b.HasIndex("TaxConfigurationId");

                    b.ToTable("Items", "Inventory");
                });

            modelBuilder.Entity("HeuristicLogix.Shared.Models.ItemSupplier", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPreferredSupplierForItem")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastPurchaseDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("LastPurchasePriceAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("SupplierInternalPartNumber")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ItemId", "SupplierId");

                    b.HasIndex("ItemId");

                    b.HasIndex("SupplierId");

                    b.ToTable("ItemSuppliers", "Purchasing");
                });

            modelBuilder.Entity("HeuristicLogix.Shared.Models.ItemUnitConversion", b =>
                {
                    b.Property<Guid>("ItemUnitConversionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ConversionFactorQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("FromUnitOfMeasureId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("ToUnitOfMeasureId")
                        .HasColumnType("int");

                    b.HasKey("ItemUnitConversionId");

                    b.HasIndex("FromUnitOfMeasureId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ToUnitOfMeasureId");

                    b.HasIndex("ItemId", "FromUnitOfMeasureId", "ToUnitOfMeasureId");

                    b.ToTable("ItemUnitConversions", "Inventory");
                });

            modelBuilder.Entity("HeuristicLogix.Shared.Models.MaterialItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<double?>("HeuristicLoadingTime")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresSpecialHandling")
                        .HasColumnType("bit");

                    b.Property<string>("SpecialHandlingNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("WeightPerUnit")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Name");

                    b.ToTable("MaterialItems", "Logistics");
                });

            modelBuilder.Entity("HeuristicLogix.Shared.Models.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("OutboxEvents", "Logistics");
                });

            modelBuilder.Entity("HeuristicLogix.Shared.Models.ProductTaxonomy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsVerifiedByExpert")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("StandardUnit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UsageCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("VerifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("WeightFactor")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.HasIndex("IsVerifiedByExpert");

                    b.HasIndex("UsageCount");

                    b.ToTable("ProductTaxonomies", "Logistics");
                });

            modelBuilder.Entity("HeuristicLogix.Shared.Models.StagingPurchaseInvoice", b =>
                {
                    b.Property<Guid>("StagingPurchaseInvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FiscalReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("InvoiceIssueDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("StagingPurchaseInvoiceId");

                    b.HasIndex("FiscalReceiptNumber");

                    b.HasIndex("SupplierId");

                    b.ToTable("StagingPurchaseInvoices", "Purchasing");
                });

            modelBuilder.Entity("HeuristicLogix.Shared.Models.StagingPurchaseInvoiceDetail", b =>
                {
                    b.Property<Guid>("StagingPurchaseInvoiceDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("ReceivedQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("StagingPurchaseInvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("UnitPriceAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("StagingPurchaseInvoiceDetailId");

                    b.HasIndex("ItemId");

                    b.HasIndex("StagingPurchaseInvoiceId");

                    b.ToTable("StagingPurchaseInvoiceDetails", "Purchasing");
                });

            modelBuilder.Entity("HeuristicLogix.Shared.Models.Supplier", b =>
                {
                    b.Property<Guid>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DefaultCreditDaysDuration")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NationalTaxIdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SupplierBusinessName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SupplierTradeName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("SupplierId");

                    b.HasIndex("NationalTaxIdentificationNumber")
                        .IsUnique();

                    b.HasIndex("SupplierBusinessName");

                    b.ToTable("Suppliers", "Purchasing");
                });

            modelBuilder.Entity("HeuristicLogix.Shared.Models.TaxConfiguration", b =>
                {
                    b.Property<Guid>("TaxConfigurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TaxName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("TaxPercentageRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("TaxConfigurationId");

                    b.HasIndex("TaxName");

                    b.ToTable("TaxConfigurations", "Core");
                });

            modelBuilder.Entity("HeuristicLogix.Shared.Models.Truck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompatibilityRules")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExpertAssignmentCount")
                        .HasColumnType("int");

                    b.Property<string>("ExpertLoadingHistory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("HeuristicCapacityScore")
                        .HasColumnType("float");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastHeuristicUpdate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TruckType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("PlateNumber")
                        .IsUnique();

                    b.ToTable("Trucks", "Logistics");
                });

            modelBuilder.Entity("HeuristicLogix.Shared.Models.UnitOfMeasure", b =>
                {
                    b.Property<int>("UnitOfMeasureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitOfMeasureId"));

                    b.Property<string>("UnitOfMeasureName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UnitOfMeasureSymbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UnitOfMeasureId");

                    b.HasIndex("UnitOfMeasureName")
                        .HasDatabaseName("IX_UnitsOfMeasure_UnitOfMeasureName");

                    b.HasIndex("UnitOfMeasureSymbol")
                        .IsUnique()
                        .HasDatabaseName("IX_UnitsOfMeasure_UnitOfMeasureSymbol");

                    b.ToTable("UnitsOfMeasure", "Core");
                });

            modelBuilder.Entity("HeuristicLogix.Shared.Models.ConduceItem", b =>
                {
                    b.HasOne("HeuristicLogix.Shared.Models.Conduce", "Conduce")
                        .WithMany("Items")
                        .HasForeignKey("ConduceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeuristicLogix.Shared.Models.ProductTaxonomy", "ProductTaxonomy")
                        .WithMany()
                        .HasForeignKey("ProductTaxonomyId");

                    b.Navigation("Conduce");

                    b.Navigation("ProductTaxonomy");
                });

            modelBuilder.Entity("HeuristicLogix.Shared.Models.Item", b =>
                {
                    b.HasOne("HeuristicLogix.Shared.Models.UnitOfMeasure", "BaseUnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("BaseUnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeuristicLogix.Shared.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HeuristicLogix.Shared.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeuristicLogix.Shared.Models.UnitOfMeasure", "DefaultSalesUnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("DefaultSalesUnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HeuristicLogix.Shared.Models.TaxConfiguration", "TaxConfiguration")
                        .WithMany()
                        .HasForeignKey("TaxConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaseUnitOfMeasure");

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("DefaultSalesUnitOfMeasure");

                    b.Navigation("TaxConfiguration");
                });

            modelBuilder.Entity("HeuristicLogix.Shared.Models.ItemSupplier", b =>
                {
                    b.HasOne("HeuristicLogix.Shared.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeuristicLogix.Shared.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("HeuristicLogix.Shared.Models.ItemUnitConversion", b =>
                {
                    b.HasOne("HeuristicLogix.Shared.Models.UnitOfMeasure", "FromUnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("FromUnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeuristicLogix.Shared.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeuristicLogix.Shared.Models.UnitOfMeasure", "ToUnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("ToUnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromUnitOfMeasure");

                    b.Navigation("Item");

                    b.Navigation("ToUnitOfMeasure");
                });

            modelBuilder.Entity("HeuristicLogix.Shared.Models.StagingPurchaseInvoice", b =>
                {
                    b.HasOne("HeuristicLogix.Shared.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("HeuristicLogix.Shared.Models.StagingPurchaseInvoiceDetail", b =>
                {
                    b.HasOne("HeuristicLogix.Shared.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeuristicLogix.Shared.Models.StagingPurchaseInvoice", "StagingPurchaseInvoice")
                        .WithMany("Details")
                        .HasForeignKey("StagingPurchaseInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("StagingPurchaseInvoice");
                });

            modelBuilder.Entity("HeuristicLogix.Shared.Models.Conduce", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("HeuristicLogix.Shared.Models.StagingPurchaseInvoice", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
