# HeuristicLogix Infrastructure - Terraform Configuration
# Docker Provider for Local Development & Production Deployment

terraform {
  required_version = ">= 1.0"
  
  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "~> 3.0"
    }
  }
}

# Configure Docker provider
provider "docker" {
  host = "npipe:////./pipe/docker_engine" # Windows
  # host = "unix:///var/run/docker.sock"  # Linux/Mac - uncomment if needed
}

# Variables
variable "sql_password" {
  description = "SQL Server SA password (must meet complexity requirements)"
  type        = string
  sensitive   = true
  default     = "HeuristicLogix2026!"
}

variable "kafka_port" {
  description = "Kafka bootstrap server port"
  type        = number
  default     = 9092
}

variable "api_port" {
  description = "API service port"
  type        = number
  default     = 5000
}

variable "ui_port" {
  description = "Blazor UI port"
  type        = number
  default     = 5001
}

variable "ai_port" {
  description = "Python AI service port"
  type        = number
  default     = 8000
}

# Docker Network - Isolated bridge network
resource "docker_network" "heuristic_net" {
  name   = "heuristic_net"
  driver = "bridge"
  
  ipam_config {
    subnet  = "172.28.0.0/16"
    gateway = "172.28.0.1"
  }
  
  labels {
    label = "project"
    value = "heuristiclogix"
  }
  
  labels {
    label = "environment"
    value = "production"
  }
}

# Docker Volumes - Named volumes for persistence
resource "docker_volume" "sql_data" {
  name = "sql_data"
  
  labels {
    label = "service"
    value = "database"
  }
  
  labels {
    label = "project"
    value = "heuristiclogix"
  }
}

resource "docker_volume" "kafka_logs" {
  name = "kafka_logs"
  
  labels {
    label = "service"
    value = "kafka"
  }
  
  labels {
    label = "project"
    value = "heuristiclogix"
  }
}

resource "docker_volume" "zk_data" {
  name = "zk_data"
  
  labels {
    label = "service"
    value = "zookeeper"
  }
  
  labels {
    label = "project"
    value = "heuristiclogix"
  }
}

resource "docker_volume" "ai_model_cache" {
  name = "ai_model_cache"
  
  labels {
    label = "service"
    value = "ai_brain"
  }
  
  labels {
    label = "project"
    value = "heuristiclogix"
  }
}

# Generate .env file with connection strings
resource "local_file" "env_file" {
  filename = "${path.root}/../../.env"
  
  content = <<-EOT
# HeuristicLogix Environment Configuration
# Generated by Terraform - DO NOT EDIT MANUALLY

# SQL Server Configuration
SQLSERVER_HOST=db_sql
SQLSERVER_PORT=1433
SQLSERVER_DATABASE=HeuristicLogixDB
SQLSERVER_USER=sa
SQLSERVER_PASSWORD=${var.sql_password}
SQLSERVER_CONNECTION_STRING=Server=db_sql,1433;Database=HeuristicLogixDB;User Id=sa;Password=${var.sql_password};TrustServerCertificate=True;MultipleActiveResultSets=True;

# Kafka Configuration
KAFKA_BOOTSTRAP_SERVERS=kafka_bus:${var.kafka_port}
KAFKA_TOPIC_EXPERT_DECISIONS=expert.decisions.v1
KAFKA_TOPIC_HISTORIC_DELIVERIES=historic.deliveries.v1
KAFKA_CONSUMER_GROUP=heuristiclogix-intelligence

# Zookeeper Configuration
ZOOKEEPER_HOST=zookeeper
ZOOKEEPER_PORT=2181

# API Configuration
API_BASE_URL=http://api_logistics:${var.api_port}
API_PORT=${var.api_port}

# UI Configuration
UI_BASE_URL=http://ui_blazor:${var.ui_port}
UI_PORT=${var.ui_port}

# AI Configuration
AI_SERVICE_URL=http://ai_brain:${var.ai_port}
AI_PORT=${var.ai_port}
GEMINI_API_KEY=your-gemini-api-key-here

# Network Configuration
DOCKER_NETWORK=heuristic_net

# Application Configuration
ASPNETCORE_ENVIRONMENT=Production
ASPNETCORE_URLS=http://+:${var.api_port}
TZ=America/Santo_Domingo

# Monitoring & Logging
LOG_LEVEL=Information
ENABLE_DETAILED_ERRORS=false
ENABLE_METRICS=true

# Security
CORS_ALLOWED_ORIGINS=http://localhost:${var.ui_port},http://ui_blazor:${var.ui_port}
JWT_SECRET=your-jwt-secret-key-change-in-production
EOT

  file_permission = "0644"
}

# Outputs
output "network_id" {
  description = "Docker network ID"
  value       = docker_network.heuristic_net.id
}

output "network_name" {
  description = "Docker network name"
  value       = docker_network.heuristic_net.name
}

output "volumes" {
  description = "Created Docker volumes"
  value = {
    sql_data        = docker_volume.sql_data.name
    kafka_logs      = docker_volume.kafka_logs.name
    zk_data         = docker_volume.zk_data.name
    ai_model_cache  = docker_volume.ai_model_cache.name
  }
}

output "connection_strings" {
  description = "Application connection strings"
  sensitive   = true
  value = {
    sqlserver = "Server=db_sql,1433;Database=HeuristicLogixDB;User Id=sa;Password=${var.sql_password};TrustServerCertificate=True;"
    kafka     = "kafka_bus:${var.kafka_port}"
  }
}

output "service_urls" {
  description = "Service URLs"
  value = {
    api = "http://localhost:${var.api_port}"
    ui  = "http://localhost:${var.ui_port}"
    ai  = "http://localhost:${var.ai_port}"
  }
}
